export const SET_KLINES ='SET_KLINES'
export const ADD_OFFCHART_INDICATOR ='ADD_OFFCHART_INDICATOR'
export const SET_TIME_OFFSET ='SET_TIME_OFFSET'
export const CLEAR_OFFCHART_INDICATORS ='CLEAR_OFFCHART_INDICATORS'
